#!/bin/bash

POSTGRES_CONTAINER_NAME="my_postgres_db"
POSTGRES_USER="admin"
POSTGRES_PASSWORD="securepassword"
POSTGRES_DB="exam-api-db"
POSTGRES_PORT=5433
POSTGRES_HOST="localhost"
POSTGRES_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
LOG_LEVEL="info"
APP_NAME="exam-api-app"

# Create .env file with environment variables
cat << EOF > app/db.env
POSTGRES_CONTAINER_NAME=${POSTGRES_CONTAINER_NAME}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_HOST=${POSTGRES_HOST}
EOF

cat << EOF > app/.env
APP_NAME=${APP_NAME}
POSTGRES_URL=${POSTGRES_URL}
LOG_LEVEL=${LOG_LEVEL}
EOF